sudo: required
services:
  - docker
  
before_install:
  # You will check name of test images
  # iI'll check the errors
  - docker build -t ekolmakov/react-test2 -f ./client/Dockerfile.dev ./client

script:
  # You will check name of test images
  # - docker run ekolmakov/multi-docker npm test
  
  - docker run -e CI=true ekolmakov/react-test2 npm test
  
after_success:
  # ! private repo by default
  - docker build -t ekolmakov/multi-client2 ./client
  - docker build -t ekolmakov/multi-nginx2 ./nginx
  - docker build -t ekolmakov/multi-server2 ./server
  - docker build -t ekolmakov/multi-worker2 ./worker
  
  # Take those images and push them to docker hub
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # i have only two images at docker hub repository
  - docker push ekolmakov/multi-client2
  - docker push ekolmakov/multi-nginx2
  - docker push ekolmakov/multi-server2
  - docker push ekolmakov/multi-worker2
  
 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  # см. скриншот aws
  # ! Will we have the quotes ?
  app: "multi-docker"
  env: "MultiDocker-env"
  # Will we create new backet for multi-docker environment ?
  bucket_name: "elasticbeanstalk-us-east-2-701836065776"
  # You will see the lecture and config of s3.
  # I STOPPED IN THIS PLACE 280121 ### 
  # bucket_path: docker
  bucket_path: docker-multi

  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

